name: "Deploy to Server"


on:
  push:
    branches: 
      - main
      - feature/27-create-deployment-workflow


jobs: 
  deploy:

    runs-on: ubuntu-latest

    steps: 
    - name: "Checkout code"
      uses: actions/checkout@v2

     - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Deploy to server
      run: |
        ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} 'cd ~/discord_files && git pull origin main && dotnet publish -c Release -o output'