name: "Build the Bot"

on:
  push:
    branches: [ "main" ]  # This triggers the workflow when code is merged into main
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
    branches: [ "*" ]  # This triggers the workflow on pull requests to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
      
    - name: Restore dependencies
      run: dotnet restore
      working-directory: EdgeOfEmpireBot

    - name: Build
      run: dotnet build --no-restore
      working-directory: EdgeOfEmpireBot

#TODO - Build unit tests and validate they pass.
