name: Deploy and Start Bot

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Restore Dependencies
        run: dotnet restore
        working-directory: EdgeOfEmpireBot

      - name: Build
        run: dotnet build --no-restore --output ../MainBotOutput
        working-directory: EdgeOfEmpireBot

      - name: Publish
        run: dotnet publish --no-restore -c Release -o ../MainBotOutput
        working-directory: EdgeOfEmpireBot

  start_bot:
    needs: build_and_deploy
    runs-on: self-hosted
    steps:
      - name: Start Bot on Server
        run: |
          sudo DISCORD_TOKEN=${DISCORD_TOKEN} DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID} /home/martinimon/scripts/start_bot.sh
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
        shell: /usr/bin/bash -e {0}
