name: Deploy to Server

on:
  push:
    branches:
      - main
      - feature/27-create-deployment-workflow

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v2

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}  # Check out the branch that triggered the workflow

    - name: Build Bot
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}  # Use environment variable for the username
      run: |
        cd ~/dev/discord_bot/EdgeOfEmpireBot
        git pull origin main
        dotnet publish EdgeOfEmpireBot.csproj -c Release -o output

    - name: Start Bot on Server
      env:
        SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}  # Obscure the username using environment variable
      run: |
        sudo -u $SERVER_USERNAME bash /home/$SERVER_USERNAME/scripts/start_bot.sh
