name: Deploy to Server

on:
  push:
    branches:
      - main
      - feature/27-create-deployment-workflow  # Add your branches here

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Deploy
      run: |
        cd ~/discord_files
        git pull origin main
        dotnet publish -c Release -o output

        #TODO expand on what needs to be done when the bot is deployed. 
