name: Deploy to Server

on:
  push:
    branches:
      - main
      - feature/27-create-deployment-workflow

jobs:
  deploy:
    runs-on: self-hosted 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Deploy
      run: |
        cd ~/dev/discord_bot
        git pull origin main
        dotnet publish -c Release -o output
        # Add any additional deployment steps here like injecting the Discord token... Need to set up a new bot for dev or prod either or. 