name: Deploy and Start Bot

on:
  push:
    branches:
      - main
      - feature/27-create-deployment-workflow

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    # - name: Clean previous build
    #   run: dotnet clean EdgeOfEmpireBot/EdgeOfEmpireBot.sln
    #   env:
    #     DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
    #   working-directory: EdgeOfEmpireBot

    - name: Restore dependencies
      run: dotnet restore
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      working-directory: EdgeOfEmpireBot

    - name: Build
      run: dotnet build --no-restore --output ../MainBotOutput
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      working-directory: EdgeOfEmpireBot

    - name: Publish
      run: dotnet publish --no-restore -c Release -o ../MainBotOutput
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      working-directory: EdgeOfEmpireBot

    - name: Start Bot on Server
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}  # Ensure the environment variable is passed to the script
      run: |
        # Export the environment variable for the current shell
        export DISCORD_TOKEN=${DISCORD_TOKEN}

        # Use sudo with -E to preserve the environment variable
        sudo -E /home/martinimon/scripts/start_bot.sh